### ISSUE TITLE
implement database migration

### ISSUE THREAD

**Issue by hcwinsemius** [localdevices/OpenRiverCam#71]
For future releases, we need to ensure databases can be migrated from one version to another.

**Comment by RickHagenaars** [comment]
To extend a little bit on this issue: We currently have the sqlalchemy library which automatically generates the database based on our data models. This does work fine for a fresh database, but if we change models and have a pre-existing database these changes do not get propagated.

This must be a quite common issue since sqlalchemy is used in the "ORM" mode often. We'll need to look at some other projects for best practices here.

For this issue, we want to have a solution for:
- Changing an existing model property (i.e. changing a database column) for instance, for instance extending the varchar size.
- Deleting a model property.
- Adding a model property.

I can imagine we'll be having a simple script which checks a version number stored in the database and have simple SQL commands for intermediate versions. Please try to keep everything database agnostic, so although we're only using postgresql now we don't loose support for other relational databases.

**Comment by RickHagenaars** [comment]
@niieq: Hessel mentioned Flask migrate for this, might want to look into that.

**Comment by niieq** [comment]
Sure. That is one of the common results. Looking further into it.
